import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import { NavigationMenuDemo } from "./_components/navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import WrapperCom from "./_components/WrapperCom/WrapperCom";
import TanStackProviders from "@/providers/TanStackProvider";
import Footer from "./_components/footer/Footer";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${exo.className} antialiased`}
      >
        <TanStackProviders>
          <WrapperCom>
            <NavigationMenuDemo />
          </WrapperCom>
          <div className="container max-w-[1200px] mx-auto">
            {children}
            <Toaster />
          </div>
          <Footer></Footer>
        </TanStackProviders>
      </body>
    </html>
  );
}
